
---
- name: Configure webserver with nginx
  hosts: webservers
  become: True
  tasks:
  - name: install nginx
    ansible.builtin.apt:
       name: nginx
       update_cache: yes
  - name: copy nginx config file
    ansible.builtin.copy:
       src: files/nginx.conf
       dest: /etc/nginx/sites-available/default
  - name: enable configuration
    ansible.builtin.file:
      dest: /etc/nginx/sites-enabled/default
      src: /etc/nginx/sites-available/default
      state: link
  - name: copy index.html
    ansible.builtin.template:
       src: templates/index.html.j2
       dest: /usr/share/nginx/html/index.html
       mode: 0644
  - name: restart nginx
    ansible.builtin.service:
       name: nginx
       state: reloaded
